### ISSUE TITLE
Tree is not used

### ISSUE THREAD

**Issue by CesMak** [hayoung-kim/mcts-tic-tac-toe#1]
Hey there,

you calculate your whole tree every time new is that correct?

But in **play.py** you might be able to use an old calculated tree in a step before?! This would save a lot of calculation time or?

**Comment by hayoung-kim** [comment]
This is not perfect implementation for MCTS. I wrote the code for understanding how MCTS works. 
However, you are correct. It would be more efficient when you use an old calculated tree. 
Thank you for your comment!

**Comment by CesMak** [comment]
Hey,

I use mcts for a card game however I think it is very hard to reuse tree cause the input state changes a lot after each of the 3 other players played a card.....

Do you have an idea how to reuse mcts tree - it is not so easy from my perspective....

**Comment by hayoung-kim** [comment]
I'm sorry I couldn't help you. I hope you solve that issue.
